# roles/pi-password/tasks/main.yml
---

   # CHANGE DEFAULT PASSWORD
- name: Set a new password for the default "pi" account
  user:
    name: pi
    password: "{{new_password | password_hash('sha512') }}"
