#TRRON Project Shane Finan.  Ansible playbook to bookstrap several Raspberry Pis Authoried by Gary Mc Dermott.
# ansible-playbook bootstrap.yml
---

- name: TRRON Raspberry Pi password
  hosts: tnodes
  become: yes
  vars_files:
    - vars.yml
  roles:
     - pi-password
